//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGPMS_application.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string server {
            get {
                return ((string)(this["server"]));
            }
            set {
                this["server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dbname {
            get {
                return ((string)(this["dbname"]));
            }
            set {
                this["dbname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int confi_stat {
            get {
                return ((int)(this["confi_stat"]));
            }
            set {
                this["confi_stat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ondutycamera {
            get {
                return ((int)(this["ondutycamera"]));
            }
            set {
                this["ondutycamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int maingate_camera {
            get {
                return ((int)(this["maingate_camera"]));
            }
            set {
                this["maingate_camera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\xampp\\xampp-control.exe")]
        public string xampp_pathfile {
            get {
                return ((string)(this["xampp_pathfile"]));
            }
            set {
                this["xampp_pathfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cust_msg_1stline {
            get {
                return ((string)(this["cust_msg_1stline"]));
            }
            set {
                this["cust_msg_1stline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM4")]
        public string gsm_port {
            get {
                return ((string)(this["gsm_port"]));
            }
            set {
                this["gsm_port"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string arduino_port {
            get {
                return ((string)(this["arduino_port"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cust_msg_2ndline {
            get {
                return ((string)(this["cust_msg_2ndline"]));
            }
            set {
                this["cust_msg_2ndline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string last_use {
            get {
                return ((string)(this["last_use"]));
            }
            set {
                this["last_use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string guard_id {
            get {
                return ((string)(this["guard_id"]));
            }
            set {
                this["guard_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int arduino_BaudRate {
            get {
                return ((int)(this["arduino_BaudRate"]));
            }
            set {
                this["arduino_BaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TmpTemperature {
            get {
                return ((string)(this["TmpTemperature"]));
            }
            set {
                this["TmpTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hello Mr/Mrs ")]
        public string line1_msg_entry {
            get {
                return ((string)(this["line1_msg_entry"]));
            }
            set {
                this["line1_msg_entry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(", Praise be Jesus and Mary! Your son/daughter")]
        public string line2_msg_entry {
            get {
                return ((string)(this["line2_msg_entry"]));
            }
            set {
                this["line2_msg_entry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("has entered the SRCB campus at")]
        public string line3_msg_entry {
            get {
                return ((string)(this["line3_msg_entry"]));
            }
            set {
                this["line3_msg_entry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("with a body temperature of ")]
        public string line4_msg_entry {
            get {
                return ((string)(this["line4_msg_entry"]));
            }
            set {
                this["line4_msg_entry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(". Thank you.")]
        public string line5_msg_entry {
            get {
                return ((string)(this["line5_msg_entry"]));
            }
            set {
                this["line5_msg_entry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("St. Rita\'s College of Balingasag")]
        public string from_msg_entry {
            get {
                return ((string)(this["from_msg_entry"]));
            }
            set {
                this["from_msg_entry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera_status {
            get {
                return ((string)(this["Camera_status"]));
            }
            set {
                this["Camera_status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Current_UserExit {
            get {
                return ((string)(this["Current_UserExit"]));
            }
            set {
                this["Current_UserExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_msgentro_exit {
            get {
                return ((string)(this["Txt_msgentro_exit"]));
            }
            set {
                this["Txt_msgentro_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_msg_afterStudent_name_exit {
            get {
                return ((string)(this["Txt_msg_afterStudent_name_exit"]));
            }
            set {
                this["Txt_msg_afterStudent_name_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_msg_afterdate_exit {
            get {
                return ((string)(this["Txt_msg_afterdate_exit"]));
            }
            set {
                this["Txt_msg_afterdate_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Txt_endmsg_exit {
            get {
                return ((string)(this["Txt_endmsg_exit"]));
            }
            set {
                this["Txt_endmsg_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string guard_on_duty {
            get {
                return ((string)(this["guard_on_duty"]));
            }
            set {
                this["guard_on_duty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string toogle_restrict18 {
            get {
                return ((string)(this["toogle_restrict18"]));
            }
            set {
                this["toogle_restrict18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int youngest {
            get {
                return ((int)(this["youngest"]));
            }
            set {
                this["youngest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Oldest {
            get {
                return ((int)(this["Oldest"]));
            }
            set {
                this["Oldest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Praise be Jesus and Mary! Your child")]
        public string Txt_intro_restrict_msg {
            get {
                return ((string)(this["Txt_intro_restrict_msg"]));
            }
            set {
                this["Txt_intro_restrict_msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("is not permitted to enter\r\nthe school campus due to age restriction from ages")]
        public string Txt_after_restrict_msg {
            get {
                return ((string)(this["Txt_after_restrict_msg"]));
            }
            set {
                this["Txt_after_restrict_msg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("and below.\r\nPlease follow government pandemic protocals and keep your child safe." +
            "\r\n\r\nThis is an automated message, please do not reply.")]
        public string Txt_end_restrict_msg {
            get {
                return ((string)(this["Txt_end_restrict_msg"]));
            }
            set {
                this["Txt_end_restrict_msg"] = value;
            }
        }
    }
}
